# Site settings
title: Gavin Blog
SEOTitle: Gavin的博客 | Gavin Blog
header-img: img/post-bg-desk.jpg
email: wswxg@gmail.com
description: "Doubt is the key to knowledge."
keyword: "Gavin, Gavin Blog, 博客, Java, Linux, Openwrt"
url: "http://vectorstone.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/vectorstone/vectorstone.github.io.git" # you code repository
# https://github.com/qiubaiying/qiubaiying.github.io.git
# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Life is real, life is earnest."
sidebar-avatar: /img/sidebar-avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     
github_username:    vectorstone
facebook_username:  
jianshu_username:   
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 21f97d78477fcec55984                          #生成的clientID
  clientSecret: f45129cc83f9638766efdc09b82f96d6f2907eaa    #生成的clientSecret
  repo: vectorstone.github.io    #存储你评论 issue 的 Github 仓库名（建议直接用 GitHub Page 的仓库名）
  owner: vectorstone    #github用户名
  admin: vectorstone   # 这个仓库的管理员，可以有多个，用数组表示，一般写自己,
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
  id: 'window.location.pathname' #页面的唯一标识，gitalk 会根据这个标识自动创建的issue的标签,我们使用页面的相对路径作为标识


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
#    {
#        title: "WY",
#        href: "http://zhengwuyang.com"
#    },{
#        title: "简书·BY",
#        href: "http://www.jianshu.com/u/e71990ada2fd"
#    },{
#        title: "Apple",
#        href: "https://apple.com"
#    },{
#        title: "Apple Developer",
#        href: "https://developer.apple.com/"
#    }
#]

plugins: [jekyll-paginate]